### User Profile
GET http://localhost:3000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGI1ZTY5MTMwNjQxOWZhM2I4NjM1ODYiLCJpYXQiOjE2ODk2NDI2NDMsImV4cCI6MTY4OTY0NjI0M30.yTsyBjZORj4bFjd_nYdRk5Htc3NZ6KSiB7mxXa1gmSE

###
### User Registration
###

### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "john",
  "email": "john@example.com",
  "password": "123456"
}

###

### User Login
###

### User login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "john",
  "password": "123456"
}

