### User Profile
GET http://localhost:3000/users/profile
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NGI2OTU1YTUyMzIyNWJjOGFjMGEzYWUiLCJpYXQiOjE2ODk2ODczOTksImV4cCI6MTY4OTY5MDk5OX0.HtDsyuH15hGva4wwa1JIUDXvNDHXpgonKHN42ScL99c

###
### User Registration
###

### Register a new user
POST http://localhost:3000/users/register
Content-Type: application/json

{
  "username": "Poppy",
  "email": "Poppy@example.com",
  "password": "321321"
}

###

### User Login
###

### User login
POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "Poppy",
  "password": "321321"
}

